# Generated by Django 2.1.1 on 2018-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
