# Generated by Django 2.1.1 on 2018-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanage',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projectmanage',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='projectmanage',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='projectmanage',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='名称'),
        ),
    ]
