# Generated by Django 2.1.1 on 2018-11-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
